"""Add langchain_config to agents table

Revision ID: b475b14b52f2
Revises: 6d346692fe5d
Create Date: 2025-11-18 10:01:17.149841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b475b14b52f2'
down_revision: Union[str, None] = '6d346692fe5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_agent_call_statistics_agent_id'), table_name='agent_call_statistics')
    op.drop_index(op.f('idx_agent_call_statistics_call_type'), table_name='agent_call_statistics')
    op.drop_index(op.f('idx_agent_call_statistics_called_at'), table_name='agent_call_statistics')
    op.drop_index(op.f('idx_agent_call_statistics_date'), table_name='agent_call_statistics')
    op.drop_index(op.f('idx_agent_call_statistics_user_id'), table_name='agent_call_statistics')
    op.create_index(op.f('ix_agent_call_statistics_agent_id'), 'agent_call_statistics', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_call_statistics_call_type'), 'agent_call_statistics', ['call_type'], unique=False)
    op.create_index(op.f('ix_agent_call_statistics_called_at'), 'agent_call_statistics', ['called_at'], unique=False)
    op.create_index(op.f('ix_agent_call_statistics_date'), 'agent_call_statistics', ['date'], unique=False)
    op.create_index(op.f('ix_agent_call_statistics_user_id'), 'agent_call_statistics', ['user_id'], unique=False)

    # Add langchain_config column if it doesn't exist
    # Check if column exists to make migration idempotent
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('agents')]

    if 'langchain_config' not in columns:
        op.add_column('agents', sa.Column('langchain_config', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_agents_deployed_at'), table_name='agents')
    op.drop_index(op.f('ix_agents_deployed_by'), table_name='agents')
    op.drop_index(op.f('idx_deployment_logs_agent_id'), table_name='deployment_logs')
    op.create_index(op.f('ix_deployment_logs_agent_id'), 'deployment_logs', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployment_logs_agent_id'), table_name='deployment_logs')
    op.create_index(op.f('idx_deployment_logs_agent_id'), 'deployment_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agents_deployed_by'), 'agents', ['deployed_by'], unique=False)
    op.create_index(op.f('ix_agents_deployed_at'), 'agents', ['deployed_at'], unique=False)

    # Drop langchain_config column
    op.drop_column('agents', 'langchain_config')
    op.drop_index(op.f('ix_agent_call_statistics_user_id'), table_name='agent_call_statistics')
    op.drop_index(op.f('ix_agent_call_statistics_date'), table_name='agent_call_statistics')
    op.drop_index(op.f('ix_agent_call_statistics_called_at'), table_name='agent_call_statistics')
    op.drop_index(op.f('ix_agent_call_statistics_call_type'), table_name='agent_call_statistics')
    op.drop_index(op.f('ix_agent_call_statistics_agent_id'), table_name='agent_call_statistics')
    op.create_index(op.f('idx_agent_call_statistics_user_id'), 'agent_call_statistics', ['user_id'], unique=False)
    op.create_index(op.f('idx_agent_call_statistics_date'), 'agent_call_statistics', ['date'], unique=False)
    op.create_index(op.f('idx_agent_call_statistics_called_at'), 'agent_call_statistics', ['called_at'], unique=False)
    op.create_index(op.f('idx_agent_call_statistics_call_type'), 'agent_call_statistics', ['call_type'], unique=False)
    op.create_index(op.f('idx_agent_call_statistics_agent_id'), 'agent_call_statistics', ['agent_id'], unique=False)
    # ### end Alembic commands ###
