"""Initial migration - create llm_models and platform_statistics tables

Revision ID: 12c762aa1c6b
Revises: 
Create Date: 2025-10-30 03:45:19.051781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12c762aa1c6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.Column('total_agents', sa.Integer(), nullable=False),
    sa.Column('production_agents', sa.Integer(), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('total_api_calls', sa.Integer(), nullable=False),
    sa.Column('llm_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_statistics_date'), 'platform_statistics', ['date'], unique=True)
    op.drop_index(op.f('ix_statistics_date'), table_name='statistics')
    op.drop_table('statistics')
    op.add_column('llm_models', sa.Column('api_key_encrypted', sa.Text(), nullable=True))
    op.add_column('llm_models', sa.Column('model_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('llm_models', 'provider',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_column('llm_models', 'api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_models', sa.Column('api_key', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.alter_column('llm_models', 'provider',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('llm_models', 'model_config')
    op.drop_column('llm_models', 'api_key_encrypted')
    op.create_table('statistics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('total_users', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active_users', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_agents', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('production_agents', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_sessions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_api_calls', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('statistics_pkey'))
    )
    op.create_index(op.f('ix_statistics_date'), 'statistics', ['date'], unique=False)
    op.drop_index(op.f('ix_platform_statistics_date'), table_name='platform_statistics')
    op.drop_table('platform_statistics')
    # ### end Alembic commands ###
